source 'https://rubygems.org'
gem 'keen'
gem 'activesupport', require: "active_support/all" #for datetime calculation e.g. weeks.ago.at_beginning_of_week
gem 'rubyzip', '~> 1.3.0'
gem 'simple_xlsx_writer', require: "simple_xlsx"   #for outputting excel files
